version: '3'
services:
  neobase-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: neobase-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - IS_DOCKER=${IS_DOCKER}
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - MAX_CHATS_PER_USER=${MAX_CHATS_PER_USER}
      - NEOBASE_ADMIN_USERNAME=${NEOBASE_ADMIN_USERNAME}
      - NEOBASE_ADMIN_PASSWORD=${NEOBASE_ADMIN_PASSWORD}
      - SCHEMA_ENCRYPTION_KEY=${SCHEMA_ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - USER_JWT_EXPIRATION_MILLISECONDS=${USER_JWT_EXPIRATION_MILLISECONDS}
      - USER_JWT_REFRESH_EXPIRATION_MILLISECONDS=${USER_JWT_REFRESH_EXPIRATION_MILLISECONDS}
      - NEOBASE_MONGODB_URI=${NEOBASE_MONGODB_URI}
      - NEOBASE_MONGODB_NAME=${NEOBASE_MONGODB_NAME}
      - NEOBASE_REDIS_HOST=${NEOBASE_REDIS_HOST}
      - NEOBASE_REDIS_PORT=${NEOBASE_REDIS_PORT}
      - NEOBASE_REDIS_USERNAME=${NEOBASE_REDIS_USERNAME}
      - NEOBASE_REDIS_PASSWORD=${NEOBASE_REDIS_PASSWORD}
      - DEFAULT_LLM_CLIENT=${DEFAULT_LLM_CLIENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_MAX_COMPLETION_TOKENS=${OPENAI_MAX_COMPLETION_TOKENS}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GEMINI_MAX_COMPLETION_TOKENS=${GEMINI_MAX_COMPLETION_TOKENS}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE}
      - EXAMPLE_DB_TYPE=${EXAMPLE_DB_TYPE}
      - EXAMPLE_DB_HOST=${EXAMPLE_DB_HOST}
      - EXAMPLE_DB_PORT=${EXAMPLE_DB_PORT}
      - EXAMPLE_DB_NAME=${EXAMPLE_DB_NAME}
      - EXAMPLE_DB_USERNAME=${EXAMPLE_DB_USERNAME}
      - EXAMPLE_DB_PASSWORD=${EXAMPLE_DB_PASSWORD}
    networks:
      - neobase-network

  neobase-client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args: # These are the environment variables for the client
        - VITE_FRONTEND_BASE_URL=${VITE_FRONTEND_BASE_URL}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
    container_name: neobase-client
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - neobase-backend
    networks:
      - neobase-network

networks:
  neobase-network:
    driver: bridge
    external: true
